// Generated by CoffeeScript 1.6.2
exports.task = function(request, response) {
  var column, query, value;

  column = request.params.column;
  value = request.params.value;
  query = new Parse.Query('User');
  return query.find({
    success: function(results) {
      var user, _i, _len, _results;

      Parse.Cloud.useMasterKey();
      _results = [];
      for (_i = 0, _len = results.length; _i < _len; _i++) {
        user = results[_i];
        _results.push(user.set(column, value).save());
      }
      return _results;
    },
    error: function(results) {
      return response.error();
    }
  });
};
