// Generated by CoffeeScript 1.6.2
var ranks_percentages, _;

ranks_percentages = require('cloud/ranks_percentages.js');

_ = require('underscore');

exports.task = function(request, response) {
  var decreaseUsersRank, increaseUsersRank, query;

  increaseUsersRank = function(numberToKeep, users) {
    var guys, user, _i, _len;

    guys = _.first(users, numberToKeep);
    for (_i = 0, _len = guys.length; _i < _len; _i++) {
      user = guys[_i];
      user.increment('rank');
    }
    return guys;
  };
  decreaseUsersRank = function(numberToKeep, users) {
    var guys, user, _i, _len;

    guys = _.last(users, numberToKeep);
    for (_i = 0, _len = guys.length; _i < _len; _i++) {
      user = guys[_i];
      user.increment('rank', -1);
    }
    return guys;
  };
  query = new Parse.Query('User');
  query.descending('score');
  return query.find({
    success: function(results) {
      var downedGuys, number, percents, players, playersNumber, playersPerRank, rank, uppedGuys, user, _i, _len;

      Parse.Cloud.useMasterKey();
      playersPerRank = _.groupBy(results, function(player) {
        return player.get('rank');
      });
      for (rank in playersPerRank) {
        players = playersPerRank[rank];
        playersNumber = players.length;
        if (!(players.length > 0)) {
          return;
        }
        percents = ranks_percentages[rank - 1];
        if (!percents) {
          return;
        }
        if ((number = Math.ceil(playersNumber * percents.up / 100)) > 0) {
          uppedGuys = increaseUsersRank(number, players);
        }
        if ((number = Math.ceil(playersNumber * percents.down / 100)) > 0) {
          downedGuys = decreaseUsersRank(number, players);
        }
        for (_i = 0, _len = players.length; _i < _len; _i++) {
          user = players[_i];
          user.set('score', 0).set('game_row', 0).save();
        }
      }
    }
  });
};
