// Generated by CoffeeScript 1.6.2
exports.task = function(request, response) {
  var friendsId, query;

  friendsId = request.params.friendsId;
  query = new Parse.Query('User');
  query.containedIn('fb_id', friendsId);
  return query.find({
    success: function(results) {
      var user;

      return response.success((function() {
        var _i, _len, _results;

        _results = [];
        for (_i = 0, _len = results.length; _i < _len; _i++) {
          user = results[_i];
          _results.push({
            friend: true,
            fb_id: user.get('fb_id'),
            username: user.get('username'),
            object_id: user.id,
            score: user.get('score') | 0
          });
        }
        return _results;
      })());
    }
  });
};
