// Generated by CoffeeScript 1.6.2
var utils, _;

utils = require('cloud/utilities.js');

_ = require("underscore");

exports.task = function(request, response) {
  var friendsId, playerId, playerQuery;

  playerId = request.params.userId;
  friendsId = request.params.friendsId;
  playerQuery = new Parse.Query('User');
  return playerQuery.get(playerId, {
    success: function(player) {
      var query;

      query = new Parse.Query('User');
      query.containedIn('fb_id', friendsId);
      return query.find({
        success: function(results) {
          var index, players, user;

          results.push(player);
          results = _.uniq(results, false, function(user) {
            return user.id;
          });
          results = utils.sortByScoreAndAlphabetic(results);
          players = (function() {
            var _i, _len, _results;

            _results = [];
            for (index = _i = 0, _len = results.length; _i < _len; index = ++_i) {
              user = results[index];
              _results.push({
                friend: true,
                fb_id: user.get('fb_id'),
                username: user.get('username'),
                object_id: user.id,
                score: user.get('score') | 0,
                rank: user.get('rank') | 0,
                position: index + 1
              });
            }
            return _results;
          })();
          return response.success(players);
        }
      });
    }
  });
};
