// Generated by CoffeeScript 1.6.2
var ranks_percentages;

ranks_percentages = require('cloud/ranks_percentages.js').data;

exports.task = function(request, response) {
  var rank;

  rank = request.params.rank;
  if (rank) {
    return response.success(ranks_percentages[rank]);
  } else {
    return response.success(ranks_percentages);
  }
};
