// Generated by CoffeeScript 1.6.2
Parse.Cloud.define('getFriendsScore', function(request, response) {
  return require('cloud/friends.js').task(request, response);
});

Parse.Cloud.define('sortLeaderboard', function(request, response) {
  return require('cloud/sort_leaderboard.js').task(request, response);
});
