// Generated by CoffeeScript 1.6.2
exports.data = [
  {
    up: 95,
    down: 0
  }, {
    up: 90,
    down: 1
  }, {
    up: 80,
    down: 2
  }, {
    up: 70,
    down: 4
  }, {
    up: 60,
    down: 8
  }, {
    up: 50,
    down: 16
  }, {
    up: 40,
    down: 32
  }, {
    up: 30,
    down: 48
  }, {
    up: 20,
    down: 64
  }, {
    up: 0,
    down: 80
  }
];
