// Generated by CoffeeScript 1.6.2
exports.task = function(request, response) {
  var player_id, query;

  player_id = request.params.player_id;
  query = new Parse.Query('GameScore');
  query.equalTo('player_id', player_id);
  return query.first({
    success: function(game_score) {
      Parse.Cloud.useMasterKey();
      if (!game_score) {
        game_score = new Parse.Object('GameScore');
        game_score.set('player_id', player_id);
      }
      game_score.set('score', request.params.score);
      game_score.save();
      return response.success();
    },
    error: function(results) {
      return response.error();
    }
  });
};
