// Generated by CoffeeScript 1.6.2
var _;

_ = require("underscore");

exports.task = function(request, response) {
  var fetchUsers, query, userId, userRank;

  userRank = request.params.rank;
  userId = request.params.userId;
  query = new Parse.Query('User');
  query.equalTo('rank', userRank);
  query.descending('score');
  query.find({
    success: function(results) {
      var data, i;

      i = 0;
      while (results[i].id !== userId) {
        i++;
      }
      data = {
        total: results.length
      };
      if (i < 8) {
        data.players = fetchUsers(results, 0, 9);
        return response.success(data);
      } else if (i > results.length - 5) {
        data.players = fetchUsers(results, 0, 2).concat(fetchUsers(results, results.length - 7, results.length - 1));
        return response.success(data);
      } else {
        data.players = fetchUsers(results, 0, 2).concat(fetchUsers(results, i - 3, i + 3));
        return response.success(data);
      }
    },
    error: function(results) {
      return response.error('toto');
    }
  });
  return fetchUsers = function(users, minIndex, maxIndex) {
    var i, players, user;

    return players = ((function() {
      var _i, _len, _results;

      _results = [];
      for (i = _i = 0, _len = users.length; _i < _len; i = ++_i) {
        user = users[i];
        _results.push({
          username: user.get('username'),
          object_id: user.id,
          fb_id: user.get('fb_id'),
          score: user.get('score'),
          rank: userRank,
          position: i + 1
        });
      }
      return _results;
    })()).slice(minIndex, +maxIndex + 1 || 9e9);
  };
};
