// Generated by CoffeeScript 1.6.2
var strcmpNoLength;

strcmpNoLength = function(str1, str2) {
  var char, charIndex, longer, multi, shorter, _i, _len;

  if (str1 === str2) {
    return 0;
  }
  if (str1.length > str2.length) {
    longer = str1;
    shorter = str2;
    multi = 1;
  } else {
    longer = str2;
    shorter = str1;
    multi = -1;
  }
  for (charIndex = _i = 0, _len = longer.length; _i < _len; charIndex = ++_i) {
    char = longer[charIndex];
    if (char === shorter[charIndex]) {
      continue;
    }
    return (char > shorter[charIndex] ? 1 : -1) * multi;
  }
};

exports.sortByScoreAndAlphabetic = function(players) {
  return players.sort(function(p1, p2) {
    var deltaScore;

    deltaScore = p2.get('score') - p1.get('score');
    if (deltaScore !== 0) {
      return deltaScore;
    }
    return strcmpNoLength(p1.get('username').toLowerCase(), p2.get('username').toLowerCase());
  });
};
